'use client'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from 'next-auth/react'
// import ClientLayout from './clientLayout';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/LOGO-v2.png" type="image/png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Lao:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        {/* <SessionProvider> */}
          {children}
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}


